# for local development
version: '3.7'
services:
  mongodb:
    image: mongo:latest
    container_name: mongodb_boot
    restart: always
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=testpassword1234
